name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 CET == 01:00 UTC
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v5
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: ./3d-profile-settings.json
      - name: Move files
        run: |
          mv ./profile-3d-contrib/day.svg ./day.svg
          mv ./profile-3d-contrib/night.svg ./night.svg
          rm -rf ./profile-3d-contrib
      - name: Commit & Push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A .
          git commit -m "Update readme daily"
          git push